### ISSUE TITLE
Editable.setPos

### ISSUE THREAD

**Issue by xAqweRx** [ichord/Caret.js#33]
If someone will ned - I've used for contenteditable :

           EditableCaret.prototype.setPos = function(pos) {
                var inputor, range;
                inputor = this.domInputor;

                if ( oDocument.getSelection ) {
                    var selection = oDocument.getSelection(), node;
                    range = selection.getRangeAt( 0 );

                    var getNode = function ( node ) {
                        if ( node.childNodes.length > 0 ) {
                            for ( var i = 0; i < node.childNodes.length; i++ ) {
                                var childNode = getNode( node.childNodes[i] );
                                if ( length < pos )
                                    continue;
                                return childNode;
                            }
                        } else if( node.nodeType === 3 ) {
                            length += node.nodeValue.length;
                            if( pos <= length  &&  $( node ).closest( '*[contenteditable]' ).attr('contenteditable') == 'false'  ){
                                pos += ( length - pos )+1;
                            }
                            return node;
                        }
                    }

                    if ( inputor.childNodes.length > 0 ) {
                        var length = 0;
                        for ( var i = 0; i < inputor.childNodes.length; i++ ) {
                            node = getNode( inputor.childNodes[i] );
                            if ( length < pos )
                                continue;
                            break;
                        }
                        if ( length < pos ) {
                            range.setEnd( node, node.nodeValue.length );
                        }
                        else {
                            range.setEnd( node, pos - length + node.nodeValue.length );
                        }
                    } else {
                        range.setEnd( inputor, Math.min( pos, inputor.nodeValue.length ) );
                    }

                    range.collapse( false );
                    selection.removeAllRanges();
                    selection.addRange( range );

                }  else if ( inputor.setSelectionRange ) {
                    inputor.setSelectionRange( pos, pos );
                }
                return inputor;
            };

**Comment by ichord** [comment]
thanks. But don't want it for now.
