### ISSUE TITLE
Reports wrong position when too much line (textarea is scrolling)

### ISSUE THREAD

**Issue by sarim** [ichord/Caret.js#6]
The problem is when there are many lines in the textarea, the offset top is reported incorrectly. 

Check the screenshot.
![screen shot 2013-11-30 at 2 54 33 am](https://f.cloud.github.com/assets/1235888/1647281/2ec14f12-5939-11e3-9cf5-f1716a8a81de.jpg)

Proposed solution, top = top - element.scrollTop();

**Comment by FredTouss1** [comment]
I'm facing the same issue within ckeditor (caret v0.2.1). What looks stange to me is that the caret demo shows the malfunction (see screen capture, using FF37), but the at.js demo doesn't !

![caret-demo](https://cloud.githubusercontent.com/assets/12433838/7622106/8d763088-f9cc-11e4-8dcf-8c208da7b688.png)

**Comment by ichord** [comment]
please try to update to `v0.2.2`

**Comment by FredTouss1** [comment]
After updating to v0.2.2, the problem is still there for the iframe body as soon as there's a scrollbar.
(the textearea and the contentEditable demos are OK).

BTW, the official demo page has the same trouble when scrolling the iframe at http://ichord.github.io/Caret.js/).
Any clue ?
